title: Your awesome title
theme: minima
author: joostholslag
email: info@joostholslag.nl
description: > # this means to ignore newlines until "baseurl:"
Joost Holslag's github page

# social links
twitter_username: @joostholslag
github_username:  joostholslag

show_excerpts: true # set to false to remove excerpts on the homepage
